#!/command/with-contenv /bin/bash
# shellcheck shell=bash

function INFO() {
    echo -e "[\033[32mINFO\033[0m] ${1}"
}
function ERROR() {
    echo -e "[\033[31mERROR\033[0m] ${1}"
}
function WARN() {
    echo -e "[\033[33mWARN\033[0m] ${1}"
}

INFO "以PUID=${PUID}，PGID=${PGID}的身份启动程序..."

# 更改 nt userid 和 groupid
groupmod -o -g "$PGID" nt
usermod -o -u "$PUID" nt

# 创建目录、权限设置
chown -R nt:nt "${WORKDIR}" "${HOME}" /config /usr/lib/chromium /etc/hosts